const DATA_KEY = 'feng-xinxin-portfolio-data-v4';
const OLD_KEY = 'feng-xinxin-portfolio-works-v1';
function clone(value){return JSON.parse(JSON.stringify(value));}
function migrateOld(videos){const labels={};videos.forEach(v=>{labels[v.category||'other']=v.categoryLabel||'其他作品';});return{lists:Object.entries(labels).map(([id,title])=>({id,title})),videos:videos.map(v=>({...v,listId:v.category||'other'}))};}
function getData(){try{const current=localStorage.getItem(DATA_KEY);if(current)return JSON.parse(current);}catch(error){}return clone(window.DEFAULT_PORTFOLIO_DATA);}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
const portfolioData=getData();
function renderFilters(){const row=document.querySelector('#filter-row');row.innerHTML=`<button class="filter active" data-filter="all">全部</button>`+portfolioData.lists.map(list=>`<button class="filter" data-filter="${escapeHtml(list.id)}">${escapeHtml(list.title)}</button>`).join('');}
function renderWorks(){const grid=document.querySelector('#work-grid');grid.innerHTML=portfolioData.videos.map(video=>{const list=portfolioData.lists.find(item=>item.id===video.listId);const title=escapeHtml(video.displayTitle||video.title).replace(/\n/g,'<br>');const cover=video.cover?` style="background-image:linear-gradient(rgba(12,16,22,.22),rgba(12,16,22,.52)),url('${escapeHtml(video.cover)}')"`:'';const target=video.localVideo||video.url||'#contact';const attrs=video.localVideo?`data-local-video="${escapeHtml(video.localVideo)}" data-video-title="${escapeHtml(video.title)}"`:'target="_blank" rel="noopener"';return `<a class="work-card ${video.featured?'hero-work':''}" data-category="${escapeHtml(video.listId)}" href="${escapeHtml(target)}" ${attrs}><div class="work-art theme-${escapeHtml(video.theme||'blue')} ${video.cover?'has-cover':''}"${cover}><small>${escapeHtml(video.badge||(video.localVideo?'VIDEO':'WORK'))}</small><strong>${title}</strong>${video.result?`<i>${escapeHtml(video.result)}</i>`:''}</div><div class="work-info"><span>${escapeHtml(list?.title||'视频作品')}</span><h3>${escapeHtml(video.title)}</h3><p>${escapeHtml(video.role||'内容策划 / 执行')}</p></div></a>`;}).join('');}
renderFilters();renderWorks();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('#filter-row').addEventListener('click',event=>{const button=event.target.closest('.filter');if(!button)return;document.querySelectorAll('.filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelectorAll('#work-grid .work-card').forEach(card=>card.classList.toggle('hidden',button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter));});
const videoDialog=document.querySelector('#video-dialog'),videoPlayer=videoDialog.querySelector('video');
document.addEventListener('click',event=>{const card=event.target.closest('[data-local-video]');if(!card)return;event.preventDefault();videoPlayer.src=card.dataset.localVideo;videoDialog.querySelector('p').textContent=card.dataset.videoTitle||'';videoDialog.showModal();videoPlayer.play().catch(()=>{});});
function closeVideo(){videoPlayer.pause();videoPlayer.removeAttribute('src');videoPlayer.load();videoDialog.close();}
videoDialog.querySelector('.video-close').addEventListener('click',closeVideo);videoDialog.addEventListener('click',event=>{if(event.target===videoDialog)closeVideo();});
