window.DEFAULT_PORTFOLIO_DATA={"lists":[{"id":"creative","title":"创意卖点"},{"id":"list-1784272910404","title":"口播\\长视频"},{"id":"tutorial","title":"教程干货"},{"id":"event","title":"采访内容"},{"id":"product","title":"直播预热\\高光混剪"},{"id":"list-1784273539290","title":"AIGC"}],"videos":[
{"id":"live-sticker","listId":"tutorial","title":"先交付价值，再自然植入产品","displayTitle":"一分钟教会你制作直播贴片","url":"https://www.xiaohongshu.com/discovery/item/664f1fdb0000000005005684?source=webshare&xhsshare=pc_web&xsec_token=ABV5SeNPEzlSVtnAxBo8WxI7exaxC0h0XVOI7bBjxFWpk=&xsec_source=pc_share","localVideo":"","badge":"01:00","result":"60万+播放","theme":"blue","role":"策划 / 脚本 / 出镜 / 跟拍剪辑 / 发布运营","cover":"","featured":false},
{"id":"camera-compare","listId":"creative","title":"用对比制造直观差异","displayTitle":"传统相机直播相机","url":"","localVideo":"assets/videos/1784273243887-video-5-.mp4","badge":"VS","result":"200W+","theme":"yellow","role":"策划 / 脚本 / 出镜","cover":"","featured":false},
{"id":"new-launch","title":"悬念式新品预热","displayTitle":"新品\n预热","badge":"NEW","result":"","role":"创意 / 脚本 / 执行跟进","url":"https://weixin.qq.com/sph/AizKGcEvb","theme":"coral","featured":false,"listId":"product"},
{"id":"user-interview","listId":"event","title":"从用户视角建立真实信任","displayTitle":"大众×猛玛直播相机，真实使用感受分享！","url":"https://weixin.qq.com/sph/AMjmGkXtq","localVideo":"","badge":"TALK","result":"","theme":"pink","role":"采访策划 / 现场执行 / 内容发布","cover":"","featured":false},
{"id":"event-mix","title":"直播高光回放","displayTitle":"高光时刻","badge":"LIVE","result":"","role":"策划 / 拍摄跟进 / 剪辑审核","url":"https://weixin.qq.com/sph/AwwpzbeeNi","cover":"","theme":"sky","featured":false,"listId":"product"},
{"id":"video-1784272897977","listId":"tutorial","title":"小红书推流直播\\电脑OBS怎么操作❓","displayTitle":"小红书推流直播\\电脑OBS怎么操作❓","url":"https://www.xiaohongshu.com/discovery/item/67d7fe42000000001e005ee6?source=webshare&xhsshare=pc_web&xsec_token=ABgr8Y9866sKhNjYGNPCU1SFHmj48NPlkDgYRItptvoN8=&xsec_source=pc_share","localVideo":"","badge":"","result":"20W+","theme":"purple","role":"","cover":"","featured":false},
{"id":"video-1784273149746","listId":"list-1784272910404","title":"云PC、云桌面都上云？区别到底在哪里？","displayTitle":"云PC、云桌面都上云？区别到底在哪里？","url":"","localVideo":"assets/videos/1784273102011--VS-PC-4.0-.mp4","badge":"","result":"","theme":"blue","role":"","cover":"","featured":false},
{"id":"video-1784273335351","listId":"creative","title":"神还原游戏声，原来用的是这样一个小麦克风！","displayTitle":"神还原游戏声，原来用的是这样一个小麦克风！","url":"","localVideo":"assets/videos/1784273333893-video-4-.mp4","badge":"","result":"","theme":"blue","role":"","cover":"","featured":false},
{"id":"video-1784273464799","listId":"list-1784272910404","title":"告别纠结，直播设备怎么选才不会出错？速看","displayTitle":"告别纠结，直播设备怎么选才不会出错？速看","url":"https://www.xiaohongshu.com/discovery/item/67f5e6eb000000000b017c38?source=webshare&xhsshare=pc_web&xsec_token=ABMVqyeLq1j94DFnmFP_k_jORefELH36lhHNcuj0xWSMU=&xsec_source=pc_share","localVideo":"","badge":"","result":"","theme":"yellow","role":"","cover":"","featured":false},
{"id":"video-1784273623645","listId":"list-1784273539290","title":"AI制作产品介绍视频","displayTitle":"什么是邦彦云PC？","url":"","localVideo":"assets/videos/1784273617168--PC-.mp4","badge":"","result":"","theme":"sky","role":"","cover":"","featured":false},
{"id":"video-1784273694896","listId":"list-1784273539290","title":"AI制作漫画卖点","displayTitle":"重度设计轻松运行！GPU专属算力直通","url":"","localVideo":"assets/videos/1784273662376--.mp4","badge":"","result":"","theme":"dark","role":"","cover":"","featured":false},
{"id":"video-1784273941130","listId":"event","title":"采访8K8K老师","displayTitle":"8K8K老师：从国企铁饭碗到摄影自媒体，索尼合作摄影师的破圈分享","url":"https://weixin.qq.com/sph/A8sv02lWHw","localVideo":"","badge":"","result":"","theme":"red","role":"","cover":"","featured":false},
{"id":"video-1784274051276","listId":"creative","title":"微距镜头拍摄","displayTitle":"嘈杂到沉浸式，LARKMIX小手声色","url":"","localVideo":"assets/videos/1784286585611-video-3-.mp4","badge":"","result":"","theme":"pink","role":"","cover":"","featured":false},
{"id":"video-1784274332381","listId":"list-1784272910404","title":"长视频口播","displayTitle":"性能实验室 | 解锁丝滑CAD","url":"https://weixin.qq.com/sph/A2iTybEU37","localVideo":"","badge":"","result":"","theme":"orange","role":"","cover":"","featured":false},
{"id":"video-1784274491895","listId":"list-1784272910404","title":"春节视频","displayTitle":"2026新年概念视频","url":"https://weixin.qq.com/sph/AMUVn7SZJm","localVideo":"","badge":"","result":"","theme":"dark","role":"","cover":"","featured":false},
{"id":"video-1784274868617","listId":"creative","title":"卖点视频","displayTitle":"给你长续航直播体验！探镜在，直播在！","url":"","localVideo":"assets/videos/1784274815902-video-6-.mp4","badge":"","result":"","theme":"sky","role":"","cover":"","featured":false}
]};
